# Generated by Django 4.2.14 on 2024-08-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Userdemo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DemoUser",
            new_name="ola",
        ),
    ]
