version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: DB_post
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres1_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres1_data: