# Generated by Django 5.1 on 2024-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.DeleteModel(models.college),
    ]
