# Generated by Django 5.1 on 2024-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="college",
            fields=[
                ("collegeId", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("strength", models.IntegerField()),
                ("website", models.URLField()),
            ],
        ),
    ]
