# Generated by Django 5.1 on 2024-08-25 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Principale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Qualification", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                (
                    "CollegId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demoApp.college",
                    ),
                ),
            ],
        ),
    ]
