# Generated by Django 5.1 on 2024-08-25 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(models.Principale),
    ]
