# Generated by Django 5.1 on 2024-08-26 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoApp", "0002_principale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="college",
            old_name="strength",
            new_name="age",
        ),
    ]
